2021-01-19 10:10:20,289 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(3, 2021-01-18 03:02:24) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 3, 'date_time': datetime.datetime(2021, 1, 18, 3, 2, 24), 'value': 0.525301, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:20,297 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(3, 2021-01-18 03:21:25) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 3, 'date_time': datetime.datetime(2021, 1, 18, 3, 21, 25), 'value': 0.520309, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:20,303 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(3, 2021-01-18 03:26:26) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 3, 'date_time': datetime.datetime(2021, 1, 18, 3, 26, 26), 'value': 0.538201, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:20,310 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(3, 2021-01-18 03:31:26) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 3, 'date_time': datetime.datetime(2021, 1, 18, 3, 31, 26), 'value': 0.527352, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:20,316 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(3, 2021-01-18 03:36:26) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 3, 'date_time': datetime.datetime(2021, 1, 18, 3, 36, 26), 'value': 0.522022, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:20,323 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(3, 2021-01-18 03:41:26) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 3, 'date_time': datetime.datetime(2021, 1, 18, 3, 41, 26), 'value': 0.504277, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:20,329 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(3, 2021-01-18 03:46:26) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 3, 'date_time': datetime.datetime(2021, 1, 18, 3, 46, 26), 'value': 0.503455, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:20,346 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(3, 2021-01-18 03:51:26) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 3, 'date_time': datetime.datetime(2021, 1, 18, 3, 51, 26), 'value': 0.505355, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:20,352 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(3, 2021-01-18 04:02:11) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 3, 'date_time': datetime.datetime(2021, 1, 18, 4, 2, 11), 'value': 0.517956, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:20,357 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(3, 2021-01-18 04:13:10) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 3, 'date_time': datetime.datetime(2021, 1, 18, 4, 13, 10), 'value': 0.525626, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:20,362 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(3, 2021-01-18 04:31:26) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 3, 'date_time': datetime.datetime(2021, 1, 18, 4, 31, 26), 'value': 0.529682, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:20,367 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(3, 2021-01-18 04:41:26) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 3, 'date_time': datetime.datetime(2021, 1, 18, 4, 41, 26), 'value': 0.536107, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:20,372 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(3, 2021-01-18 04:51:26) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 3, 'date_time': datetime.datetime(2021, 1, 18, 4, 51, 26), 'value': 0.542462, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:20,377 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(3, 2021-01-18 05:13:00) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 3, 'date_time': datetime.datetime(2021, 1, 18, 5, 13), 'value': 0.541388, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:20,383 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(3, 2021-01-18 05:16:26) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 3, 'date_time': datetime.datetime(2021, 1, 18, 5, 16, 26), 'value': 0.523911, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:20,388 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(3, 2021-01-18 05:31:26) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 3, 'date_time': datetime.datetime(2021, 1, 18, 5, 31, 26), 'value': 0.546671, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:20,393 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(3, 2021-01-18 05:36:26) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 3, 'date_time': datetime.datetime(2021, 1, 18, 5, 36, 26), 'value': 0.529006, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:20,398 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(3, 2021-01-18 05:41:26) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 3, 'date_time': datetime.datetime(2021, 1, 18, 5, 41, 26), 'value': 0.527435, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:20,403 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(3, 2021-01-18 06:01:56) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 3, 'date_time': datetime.datetime(2021, 1, 18, 6, 1, 56), 'value': 0.56109, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:20,408 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(3, 2021-01-18 06:21:26) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 3, 'date_time': datetime.datetime(2021, 1, 18, 6, 21, 26), 'value': 0.55927, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:20,413 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(3, 2021-01-18 06:26:26) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 3, 'date_time': datetime.datetime(2021, 1, 18, 6, 26, 26), 'value': 0.552496, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:20,418 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(3, 2021-01-18 06:46:26) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 3, 'date_time': datetime.datetime(2021, 1, 18, 6, 46, 26), 'value': 0.537826, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:20,423 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(3, 2021-01-18 06:51:26) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 3, 'date_time': datetime.datetime(2021, 1, 18, 6, 51, 26), 'value': 0.542778, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,469 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 01:35:14) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 1, 35, 14), 'value': 0.579553, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,475 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 01:39:37) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 1, 39, 37), 'value': 0.582895, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,481 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 01:44:33) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 1, 44, 33), 'value': 0.571246, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,486 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 01:50:11) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 1, 50, 11), 'value': 0.568005, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,491 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 01:56:16) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 1, 56, 16), 'value': 0.578951, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,497 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 01:58:11) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 1, 58, 11), 'value': 0.580376, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,503 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 02:07:34) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 2, 7, 34), 'value': 0.581975, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,508 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 02:19:03) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 2, 19, 3), 'value': 0.56859, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,515 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 02:21:16) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 2, 21, 16), 'value': 0.582547, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,526 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 02:26:16) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 2, 26, 16), 'value': 0.579364, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,531 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 02:38:11) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 2, 38, 11), 'value': 0.576834, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,536 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 02:41:16) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 2, 41, 16), 'value': 0.585947, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,542 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 02:55:41) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 2, 55, 41), 'value': 0.606573, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,548 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 03:11:16) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 3, 11, 16), 'value': 0.584079, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,553 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 03:21:16) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 3, 21, 16), 'value': 0.609385, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,560 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 03:31:16) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 3, 31, 16), 'value': 0.629856, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,565 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 05:11:17) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 5, 11, 17), 'value': 0.529676, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,571 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 05:16:17) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 5, 16, 17), 'value': 0.500784, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,576 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 05:26:17) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 5, 26, 17), 'value': 0.507266, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,583 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 05:31:17) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 5, 31, 17), 'value': 0.521376, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,589 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 05:36:17) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 5, 36, 17), 'value': 0.481642, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,595 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 05:41:17) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 5, 41, 17), 'value': 0.477109, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,601 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 05:46:17) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 5, 46, 17), 'value': 0.479986, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,606 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 05:55:51) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 5, 55, 51), 'value': 0.451949, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,612 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 06:05:35) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 6, 5, 35), 'value': 0.465407, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,617 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 06:11:17) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 6, 11, 17), 'value': 0.466769, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,623 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 06:16:17) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 6, 16, 17), 'value': 0.467532, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,629 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 06:26:17) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 6, 26, 17), 'value': 0.395493, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,635 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 06:31:17) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 6, 31, 17), 'value': 0.395343, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,640 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 06:36:17) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 6, 36, 17), 'value': 0.380994, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,645 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 06:41:17) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 6, 41, 17), 'value': 0.355815, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,651 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 06:46:17) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 6, 46, 17), 'value': 0.373645, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2021-01-19 10:10:24,656 - Raised an error => (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "aeronet_aod_data_list_pkey"
DETAIL:  Key (st_id, date_time)=(4, 2021-01-18 06:55:45) already exists.

[SQL: INSERT INTO public.aeronet_aod_data_list (st_id, date_time, value, type) VALUES (%(st_id)s, %(date_time)s, %(value)s, %(type)s)]
[parameters: {'st_id': 4, 'date_time': datetime.datetime(2021, 1, 18, 6, 55, 45), 'value': 0.380615, 'type': 'aod'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
